runtime: python312

entrypoint: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0

# Optional: basic autoscaling limits (keeps cost low)
automatic_scaling:
  max_instances: 2
  min_instances: 0
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.7

env_variables:
  # If you store your DB URL as an env var (recommended)
  # NEON_DSN: "postgresql://user:pass@host/db"
  STREAMLIT_SERVER_HEADLESS: "true"
